### ISSUE TITLE
Some emms bindings don't work

### ISSUE THREAD

**Issue by rahenry** [emacs-evil/evil-collection#221] opened 2019-01-14 10:53 UTC
Some bindings don't seem to work with emms and evil-collection. For example "g1", "g2" etc., and "ga", "gA" in emms-browser mode. Most other bindings work normally. I can reproduce this with the minimal config file pasted below, by running "emacs -q --load path/to/init.el", then M-x emms-browser. Please forgive me if I'm missing something obvious here.

```

(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package emms
:ensure t
  :config
  (require 'emms-setup)
  (emms-all)
  (emms-default-players)
)

(use-package evil
  :ensure t
  :init
  (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
  (setq evil-want-keybinding nil)
  :config
  (evil-mode 1))

(use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))

```

**Comment by Ambrevar** [comment] 2019-01-14 14:41
Thanks for taking time to produce a good recipe.

I can reproduce indeed.  Strange thing, [my personal Emacs config](https://gitlab.com/ambrevar/dotfiles) does not suffer from this.  I'm not sure what's happening.

Any idea, @jojojames ?

**Comment by jojojames** [comment] 2019-01-15 03:37
I don't use emms but if I find some time, I'll try and set it up and see what's up.

**Comment by jojojames** [comment] 2019-02-16 19:47
@Ambrevar Had a chance to set up EMMS, pretty cool package.

I think the culprit is this TODO in the package.

```
    "g" (lookup-key emms-browser-mode-map (kbd "W")) ;; TODO: This overrides other "g-" prefixed keys.
```

Minor comments unrelated but I'm too short on time to find the proper channels :).

It was tricky to figure out how to get metadata showing in browse-by-* functions. I think the documentation should make that front and center. After doing the "quick start" of 50k files, I found out I'd need mp3info/some other tagger to get the tags to show up on my files. :(



The find function provided doesn't seem to work on my OSX system (for whatever reason). Looks like the regex fails (or something). Using a shorter regex with -aname to get mp3/flacs worked fine for me.

Here's my crude setup in case you see anything amiss.

```
(use-package emms
  :ensure t
  :config
  (require 'emms-setup)
  (require 'emms-info)
  (require 'emms-info-mp3info) ;; Required for processing mp3s.
  (require 'emms-cue)          ;; Required for processing flacs.
  (require 'emms-mode-line)
  (require 'emms-playing-time)
  (setq emms-source-file-default-directory "~/Music/")
  (setq emms-playlist-buffer-name "*Music*")
  (setq emms-info-asynchronously t)
  (unless (eq system-type 'windows-nt)
    (setq emms-source-file-directory-tree-function
          'emms-source-file-directory-tree-find))
  (emms-all)
  (emms-default-players)
  (setq emms-info-functions '(emms-info-mp3info emms-info-cueinfo))
  (emms-mode-line 1)
  (emms-playing-time 1)
  (define-emms-simple-player afplay '(file)
    (regexp-opt '(".mp3" ".m4a" ".aac"))
    "afplay")
  (setq emms-player-list `(,emms-player-afplay))

  (setq emms-source-file-directory-tree-function
        'emms-source-file-directory-tree-find-osx)
  (defun emms-source-file-directory-tree-find-osx (dir _regex)
    "Find files with find.

Similar to `emms-source-file-directory-tree-find' but use -iname matches."
    (with-temp-buffer
      (call-process "find"
                    nil t nil
                    "-L"                  ; follow symlinks
                    (expand-file-name dir)
                    "-type" "f"
                    "-iname" "*.mp3"
                    "-o"
                    "-iname" "*.flac")
      (delete ""
              (split-string (buffer-substring (point-min)
                                              (point-max))
                            "\n")))))```

**Comment by Ambrevar** [comment] 2019-02-20 16:58
To make your life easier configuring EMMS you can call

```lisp
(emms-all)
(emms-history-load)
```

It should handle most of the boilerplate for you.  (You can remove almost everything in your config.)

To query the tags, `mp3info` is pretty bad actually.  I recommend using EMMS own tag query tool:

```lisp
      (require 'emms-info-libtag)
      (add-to-list 'emms-info-functions 'emms-info-libtag)
```

The "proper channel" is here: https://lists.gnu.org/mailman/listinfo/emms-help
Home page: https://www.gnu.org/software/emms/

I'll report your `emms-source-file-directory-tree-find-osx` macOS issue.  Thanks for digging into this!

I'll look into the `"g"` issue as soon as possible.

**Comment by Ambrevar** [comment] 2019-02-20 17:24
Aha!  Some progress: It works without `use-package`:

```lisp
(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))

(unless (package-installed-p 'use-package)
  (package-refresh-contents))

(package-install 'emms)
(package-install 'evil)
(package-install 'evil-collection)

(with-eval-after-load 'emms
  (emms-all)
  (emms-default-players))

(setq evil-want-integration t) ;; This is optional since it's already set to t by default.
(setq evil-want-keybinding nil)
(evil-mode 1)

(evil-collection-init)
```

(At this point I wonder why is `use-package` so popular.)

**Comment by Ambrevar** [comment] 2019-02-20 17:52
Should be fixed with https://github.com/emacs-evil/evil-collection/commit/b067961140af1fcfb27b379165dca5bb53168546.  @rahenry : Can you confirm?

I think there were 2 issues:
- One with the load order and emms-playlist-mode-map not being defined early enough, which broke silently with `use-package`.  I'm now setting up `emms-playlist-mode` just in time like `emms-browser`.
- One with the prefix bindings: those have to be set first, and the binding might have to be reset beforehand (not sure about that last part).

**Comment by jojojames** [comment] 2019-02-21 02:37
I get something like this let: Searching for program: No such file or directory, mpv
with those settings.

Need this for OSX,

```
  (define-emms-simple-player afplay '(file)
    (regexp-opt '(".mp3" ".m4a" ".aac"))
    "afplay")
  (setq emms-player-list `(,emms-player-afplay))
```

Looks like there's no graceful fallback or something :D, didn't look too hard though.

For libtag, my understanding was that it needed to be compiled but the melpa recipe doesn't include that part? I quickly filed it under "too much work". :)

**Comment by Ambrevar** [comment] 2019-02-21 07:45
> For libtag, my understanding was that it needed to be compiled but the melpa recipe doesn't include that part? I quickly filed it under "too much work". :)

You need to install EMMS from a port (e.g. Homebrew, Fink, Macports).

I'll look into the other issues.  Thanks for reporting!

**Comment by Ambrevar** [comment] 2019-02-21 16:52
I looked into the mpv vs. afplay issue: basically you have none of the players supported by EMMS, hence the error.

The afplay player is not supported by default, but your snippet is too limited.  It would be nice to add a complete "afplay" player to EMMS though.  I'll send an email to the mailing list.

**Comment by Ambrevar** [comment] 2019-02-21 17:25
@jojojames : Is `afplay` free software?

**Comment by jojojames** [comment] 2019-02-21 18:34
No idea. It was just the first snippet I found to make EMMS work on OSX.

**Comment by rahenry** [comment] 2019-02-23 05:06
Hi guys. I'm not able to test it just yet, but will do so in the next few days and report. Thank you for the great work!

**Closed** 2019-02-25 09:26 UTC
