### ISSUE TITLE
Binding (kbd "<tab>") in outline-minor-mode overrides org-cycle

### ISSUE THREAD

**Issue by dieggsy** [emacs-evil/evil-collection#53] opened 2017-12-06 19:18 UTC
I'd argue `org-cycle` is way more useful when you're actually in org-mode.

**Comment by Ambrevar** [comment] 2017-12-06 21:02
Strange, I never experienced it... Recipe to reproduce?
I'll try harder on my end.

**Comment by dieggsy** [comment] 2017-12-06 23:18
It may have something to do with the fact that i'm using org-mode from master? I'll try and come up with a minimal repro sometime soon.

**Comment by dieggsy** [comment] 2017-12-10 16:34
Ok, try this:

```shell
curl -L https://git.io/vbROj -o /tmp/minimal-repro.el && emacs --batch -q -l /tmp/minimal-repro.el
```
That uses [this gist](https://gist.github.com/dieggsy/bfdbbaabee07ab47bb45b8b39fdae0d3) to:

- Set `user-emacs-directory` to `/tmp/.emacs.d/`
- Install `evil` and `evil-collection` there
- Run `(evil-mode 1)` and `(evil-collection-init)`
- Visit a temporary org file and print:
  - `(emacs-version)`
  - `(org-version)`
  - `(buffer-name)`
  - `major-mode` (for the newly created buffer)
  - Contents of `*Help*` buffer after `(describe-key [tab])` (for newly created buffer)

Here's the output on my computer, with emacs 25.3 and default org:
```
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:80
Contacting host: elpa.gnu.org:80
Contacting host: melpa.org:443
Package refresh done
Installing evil...
Cloning evil-collection...

EMACS VERSION: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19)
 of 2017-09-16
ORG VERSION: 8.2.10
BUFFER NAME: test.org
BUFFER MODE: org-mode
M-x describe-key TAB RET:
<tab> runs the command outline-toggle-children, which is an
interactive compiled Lisp function in ‘outline.el’.

It is bound to <tab>, <motion-state> <tab>.

(outline-toggle-children)

Show or hide the current subtree depending on its current state.
```

**Comment by Ambrevar** [comment] 2017-12-11 09:05
Wow, you've really put in a lot of effort to automate the repro! :)

On the one hand, I'd like to say you did not have to, a simple recipe would have been enough.
On the other hand, it's a great script that's definitely going to prove handy in the future.  Thanks for sharing!

(Please keep the gist online :p)

The problem is actually very simple: you don't use evil-org, do you?
If not, then Org will inherit from the outline-mode-map keys, including `<tab>`.

I don't think there is anything we should change to Evil Collection:

- If you don't want evil-org, does it mean you want to stick to Emacs bindings?  Then simply change the initial state of org-mode, Emacs state works properly.

- Otherwise just install evil-org.

Let me know your current setup.

**Comment by dieggsy** [comment] 2017-12-11 14:20
I disagree with this solution. Even though I may use evil-org in the future, I don't now (I tried it and didn't like or ever really use it's bindings). I _do_ still use evil-mode in org-mode however, with some minimal bindings of my own. Changing to Emacs state isn't an option - I don't get vim-like modal editing that way.  I think assuming if someone doesn't want a particular evil integration that hey'd rather not use evil at all in that mode is a mistaken train of thought.

That said, I could just rebind tab myself (it's one key), but I don't think that's a permanent solution, as anyone else who decides not to use evil-org but wants evil-collections will run into this unexpected behavior. Guess I'm saying that _since_ org-mode inherits outline-mode-map keys, `evil-collection` should be a little more cautious about these.

re: the script - it's no problem at all, I had trouble coming up with a minimal recipe "by hand" so this was the easier route. I don't use package.el and so I was tripping up a bit too much on the right steps for an isolated minimal repro (that truly were repeatable). I realized I work better with elisp anyway.

**Comment by dieggsy** [comment] 2017-12-11 14:40
To reword, it seems to me like the reasoning is "this binding is fine because this other package (which is optional), when installed, solves it" and I'm not sure how I feel about that.

**Comment by Ambrevar** [comment] 2017-12-11 14:42
I totally agree with you: it's not a desirable behaviour. But what's your suggested solution then?  I'm afraid we're being hit by the fundamental drawback of inheritance: not sure there is anything we can do about it.

It's the same story with image-mode and it's inherited modes, PDF-tools and doc-view.

Slightly off-topic: what don't you like about evil-org?
(I co-authored evil-agenda :p)

**Comment by Ambrevar** [comment] 2017-12-11 14:42
Well, one thing we could definitely do: document the issue! ;)

**Comment by Ambrevar** [comment] 2017-12-11 14:44
> To reword, it seems to me like the reasoning is "this binding is fine because this other package (which is optional), when installed, solves it" and I'm not sure how I feel about that.

My initial comment was poorly phrased: the real issue here is that of inheritance and there is not much we can do but using evil-org or org-evil.

**Comment by dieggsy** [comment] 2017-12-11 15:15
Agreed about documenting. A note: interestingly, `S-<tab>` doesn't give me the same issue, but that might be because my emacs is registering shift-tab as `<S-iso-lefttab>`. 

I think there are solutions, though maybe not very pretty ones. For example, one could use menu item bindings a la `general-predicate-dispatch` (The following is just a macro expansion of that):

```emacs-lisp
(evil-define-key 'motion outline-mode-map
  (kbd "<tab>") '(menu-item "" nil :filter
                            (lambda
                              (&optional _)
                              (cond
                               ((derived-mode-p 'org-mode)
                                'org-cycle)
                               (t outline-toggle-children)))))
```
Which would do org-cycle in org-mode and fallback to outline-toggle-children.

(Side note: have you considered using general as a dependency/helper in this project? It has some nifty features - the above becomes simply:
```emacs-lisp
(evil-define-key 'motion outline-mode-map
  (kbd "<tab>") (general-predicate-dispatch 'outline-toggle-children
                  (derived-mode-p 'org-mode) 'org-cycle))
```
)

With regard to evil-org, I can't remember all the details, except that it "wasn't for me" - maybe I liked to bind too many keys that evil-org overrode (I think I don't now), or just didn't find it that useful at the time. Maybe I should have said "I'm looking to try it again soon" - It was a _while_ ago that I tried it and it seems like several additons/improvements have been made.

**Comment by Ambrevar** [comment] 2017-12-11 15:34
While your workaround would work, I'm not too sure about implementing it... It's not very general: What if another mode inherits from outline-mode?  What if other bindings have similar issues?

@jojojames Any take on this issue?

> have you considered using general as a dependency/helper in this project?

See #48.

> It was a while ago that I tried it and it seems like several additons/improvements have been made.

Went through the same route here and I'm happy with the latest versions.  I highly recommend you give it another try.
evil-org has a rather flexible configuration process.

**Comment by dieggsy** [comment] 2017-12-11 15:56
@Ambrevar I think if another mode inherits from outline-mode, that wouldn't be an issue - it wouldn't pass the check for `(derived-mode-p 'org-mode)` and would fall back to `outline-toggle-children`. Or are you saying we'd have to add a check for every mode? Could you clarify your question on other bindings?

**Comment by Ambrevar** [comment] 2017-12-11 16:09
> Or are you saying we'd have to add a check for every mode? 

Yes, the other derived mode would also have it's <tab> key overridden.

> Could you clarify your question on other bindings?

Not just <tab>, any other key that could potentially conflict :/

**Comment by dieggsy** [comment] 2017-12-11 16:23
Well, it could be something like this instead:
```emacs-lisp
(evil-define-key 'motion outline-mode-map
  (kbd "<tab>") (general-predicate-dispatch nil
                  (eq major-mode 'outline-mode) 'outline-toggle-children))
```
Which expands to
```emacs-lisp
(evil-define-key 'motion outline-mode-map
  (kbd "<tab>") '(menu-item "" nil :filter
                            (lambda
                              (&optional _)
                              (cond
                               ((eq major-mode 'outline-mode)
                                'outline-toggle-children)
                               (t nil)))))
```
Course, if you _wanted_ the binding to be inherited, this would prevent that. And yeah, I guess you'd have to do this for other conflicting bindings. While I agree it's not perfect, I'm just still not convinced that evil-collection's default should be what we go with for the stated reasons. 

On the other hand, if documented well enough, maybe the solution is "If you don't want to use evil-org, you may want to disable evil-collection-outline.el" and be done with it. I guess evil-collection can't be expected to attend to _every_ edge case.

**Comment by jojojames** [comment] 2017-12-11 16:54
This does raise the question of 'is there a value-add general adds' that we could leverage to solve this problem. Curious on your thoughts @noctuid.

As for evil-org and not using it, I wonder if it'd be easier to have a 'simple-evil-org' version that will rebind TAB for you? I think every mode working reasonably even if other modes are disabled (evil-org) in this case is a worthy goal..

This kind of runs into the defcustom/init discussions we had before but I think for now, it'd be okay to have another defcustom for org with 'none/simple/evil-org etc that swaps out the one before evil-collection-init.

@Ambrevar It does run into the same init discussions, I think we can still leave it in its 'simple' state and just add defcustoms for edge cases. If we get 10 or more 'edge cases', we can probably start visualizing a proper pattern to it.

**Comment by Ambrevar** [comment] 2017-12-12 15:37
Done: 28eb46bd4439630bcb3ef4d65c2bff7d6fc7ffe4.

The bindings are still on by default, but the behaviour is now documented.

I think we should expect Evil-Collection users to want some sort of Evil bindings for Org mode anyways, so the `tab` issue would be fixed on their end one way or another.

Let me know if that suits you.

**Comment by noctuid** [comment] 2017-12-12 19:49
> This does raise the question of 'is there a value-add general adds' that we could leverage to solve this problem. Curious on your thoughts @noctuid.

If the functionality of `general-predicate-dispatch` is ever needed/wanted in `evil-collection`, the expansion is extremely simple and could be used directly I think.

**Comment by jojojames** [comment] 2017-12-13 02:03
@noctuid I'd be curious about the utility library. I'll raise an issue in general at some point..

@Ambrevar I was thinking more along the lines of creating a 'simple org' evil version that rebinds TAB but your way seems ok too unless @dieggsy has another opinion.

**Comment by dieggsy** [comment] 2017-12-13 02:20
I'm ok with this for now, though maybe because I haven't noticed other collisions?

**Comment by Ambrevar** [comment] 2017-12-13 07:15
I think it's better to have no "dummy" org file as it sends a clear message to the user: "Evil org bindings are not here."

Adding evil-collection-org would probably raise complaints as to why the bindings are so limited.

**Comment by Ambrevar** [comment] 2017-12-26 21:49
Closing now, feel free to re-open if you'd like to improve on anything.

**Comment by jupart** [comment] 2019-06-13 14:01
New emacs user here: I don't really understand the issue completely, but I did remove evil-collection because it seemed to change "<tab>" to 'outline-toggle-children when I wanted to keep 'org-cycle.

**Comment by Ambrevar** [comment] 2019-06-13 15:07
Actually I have been having a similar issue for a while now, but with
`<backtab>` bound to outline-show-all instead of org-shifttab in normal
state.  Note that insert state gets it right.

**Comment by cvdub** [comment] 2019-07-22 18:43
> Actually I have been having a similar issue for a while now, but with `<backtab>` bound to outline-show-all instead of org-shifttab in normal state. Note that insert state gets it right.

I had this same issue, even with evil-org installed. I believe it's because evil-org binds `org-shifttab` to `<S-tab>` instead of `<backtab>`. '<S-tab>` is bound to `<backtab>`, so the evil-collection binding to `<backtab>` takes precedence.

Setting `evil-collection-outline-bind-tab-p` to `nil` fixed this issue for me, but it would probably be better if evil-org updated their binding to `<backtab>`.

**Comment by jojojames** [comment] 2019-07-23 02:59
> @noctuid I'd be curious about the utility library. I'll raise an issue in general at some point..

I probably never did this but noticed https://github.com/noctuid/general.el/issues/144 . I'm be happy with either general or a NIH evil-collection version of the same functionality. (Tangential point).

> Setting evil-collection-outline-bind-tab-p to nil fixed this issue for me, but it would probably be better if evil-org updated their binding to <backtab>.

Can you PR @cvdub . @Somelauw is pretty responsive from what I've seen.

**Comment by noctuid** [comment] 2019-07-23 22:55
Feel free to leave suggestions on that issue for what functionality you think would be useful to have. I still have to think more about what it would actually look like.

**Comment by jojojames** [comment] 2019-10-11 01:32
@noctuid 

I'm not super familiar with all the goodies general has for keybinding but I like the one @dieggsy mentioned.

```
(evil-define-key 'motion outline-mode-map
  (kbd "<tab>") (general-predicate-dispatch nil
                  (eq major-mode 'outline-mode) 'outline-toggle-children))
```

Which is way better than what it would expand to.

> Adding evil-collection-org would probably raise complaints as to why the bindings are so limited.

After some time, I agree but I also think it's weird we don't have support for org. If we could absorb evil-org, that would be nice and fix the issue nicely, IMO.

There's probably nothing left for this topic but if @Somelauw (or someone else with an evil org type package) wanted to merge evil-org into evil-collection, I think that'd be a great idea too.

**Closed by jojojames** 2019-10-11 01:32 UTC

**Comment by jojojames** [comment] 2019-10-11 01:52
@dieggsy Your curl command to do the repro is pretty cool. If there was a way to generalize that so issue reporters can use something similar, that'd be awesome.

**Comment by jojojames** [comment] 2019-10-12 17:40
I think for starters, the "how to set up emacs -Q with evil-collection + evil installed" is a good one.

From what I've seen, most reporters are hesitant to create one because it's time consuming.

After that, it'd be interesting from a "evil-collection+evil+whatever mode they're having problems with" approach to be even more automatic.

Your $1 and $2 seems interesting too, but I didn't look too closely at your black magic there, so don't have an opinion. @dieggsy
