### ISSUE TITLE
Key translation doesn't work in eshell

### ISSUE THREAD

**Issue by rosetail** [emacs-evil/evil-collection#602] opened 2022-03-06 18:53 UTC
`evil-collection-translate-key` does nothing in eshell-mode-map. I think this is related to #433, as I am affected by that issue too. I should note though that `evil-collection-translate-key` works just fine with comint-mode.

Here is the minimal config I used to confirm the issue:
```lisp
(require 'package)
(package-initialize)

(setq evil-want-keybinding nil)
(require 'evil)
(evil-mode 1)
(require 'evil-collection)
(defun my-hjkl-rotation (_mode mode-keymaps &rest _rest)
  (evil-collection-translate-key 'normal mode-keymaps
    (kbd "C-n") (kbd "C-j")
    (kbd "C-e") (kbd "C-k")
    "gn" "gj"
    "ge" "gk"))
(add-hook 'evil-collection-setup-hook #'my-hjkl-rotation)
(evil-collection-init)
```

**Comment by condy0919** [comment] 2022-03-09 09:16
Yes, confirmed.

**Comment by condy0919** [comment] 2022-03-09 09:38
`evil-collection-eshell-mode-map-normal-state-backup-map` is nil, `lookup-key` on it will always be failed. Let me digger.

**Comment by rosetail** [comment] 2022-03-27 02:55
I just noticed that translations don't work for emms either

**Comment by condy0919** [comment] 2022-03-29 16:37
....

**Comment by jojojames** [comment] 2022-04-14 05:23
fwiw, this works for me:

```
(evil-collection-translate-key 'normal 'eshell-mode-map
    "gj" "gk"
    "gk" "gj"
    :destructive t)
```

Can you try that first and if that works, can you provide the values being passed to: 

```
(evil-collection-translate-key 'normal mode-keymaps
    (kbd "C-n") (kbd "C-j")
    (kbd "C-e") (kbd "C-k")
    "gn" "gj"
    "ge" "gk")
```

**Comment by jojojames** [comment] 2022-04-14 21:48
So translations like this:

```
(evil-collection-translate-key 'normal 'eshell-mode-map
    "gj" "gk"
    "gk" "gj"
    :destructive t)
```

Will work but when using:

```
(add-hook 'evil-collection-setup-hook #'my-hjkl-rotation)
```

The hook for eshell is ran too early, the keybinds aren't mapped yet. Looks like we already have a FAQ section for this (which also affects key translation). https://github.com/emacs-evil/evil-collection#faq

```
Unintialized mode maps in evil-collection-setup-hook. evil-collection-setup-hook is ran with a list of keymaps passed into it. Some misconfigured modes may not have yet initialized their keymap at this time so the value of the variable may be nil. In that case, an alternative is to use a mode-hook to do any custom settings.
(add-hook 'evil-collection-setup-hook
          (lambda (_mode keymaps)
            (add-hook 'ediff-mode-hook
                      (lambda ()
                        (... keymaps ...)))))
    
View https://github.com/emacs-evil/evil-collection/issues/196 for more info.
```

Created PR to fix this.

Was able to test against eshell with this translation setup:

```
  (defun my-hjkl-rotation (_mode mode-keymaps &rest _rest)
    (evil-collection-swap-key 'normal mode-keymaps
      (kbd "C-n") (kbd "C-j")
      (kbd "C-e") (kbd "C-k")
      "gn" "gj"
      "ge" "gk"
      ;; :destructive t
      )
    ;; (evil-collection-translate-key 'normal mode-keymaps
    ;;   (kbd "C-n") (kbd "C-j")
    ;;   (kbd "C-e") (kbd "C-k")
    ;;   "gn" "gj"
    ;;   "ge" "gk")
    ;;
    )
  (add-hook 'evil-collection-setup-hook #'my-hjkl-rotation)
```

and have translations work properly.

Going to close this and work on it through the PR. Feel free to re-open.

**Closed by jojojames** 2022-04-14 21:48 UTC
