### ISSUE TITLE
Customizable initial/primary state

### ISSUE THREAD

**Issue by noctuid** [emacs-evil/evil-collection#21] opened 2017-11-08 22:08 UTC
I prefer to never actually enter motion state and only use the keymap for actual motions.

**Comment by Ambrevar** [comment] 2017-11-08 22:23
Could you be more specific?  What is your prefered state?  Use case?  Which modes?

Evil motion state is meant for modes where text insertion is not possible.

**Comment by noctuid** [comment] 2017-11-08 22:53
I always use normal state everywhere. My global keybindings are all made in normal state. A couple of the default keybindings in normal state also make sense when text insertion isn't possible (e.g. yanking and macro recording). For me, using motion state just makes things unnecessarily complicated because now I have to bind things that I would normally bind in just normal state in both normal in motion state. That or I'd have to bind all these keys in motion state and unbind some of the defaults in normal state.

**Comment by jojojames** [comment] 2017-11-09 01:54
Is there a list of tradeoffs for motion vs normal state?

I'd prefer not only to make this customizable but actually default to normal state if there weren't any obvious downsides.

It makes the transition easier for modes that can technically be in motion state but can be toggled into an editing state. Occur/Ag/Rg/Dired/etc are some that are like that.

**Comment by Ambrevar** [comment] 2017-11-09 07:17
The main downside of using normal state for read-only modes is that _all the insertion keys_ (and that's lots of them) have to be unbound/rebound.

As for the global question, off the top of my head there is some inheritance at work, but I have to look into this.
Otherwise, if your key is truly global (i.e. also for insertion), use `global-set-key`, and if your key should be global in both normal and motion state, it's trivial to do so with `evil-global-set-key`.

I'm against switching to normal state because that's not how Evil was designed.  The motion state is here for a purpose.

I'll investigate further.

**Comment by jojojames** [comment] 2017-11-09 16:48
I'm not sure I follow why they have to be unbound.

For the case where there's a key "under" evil's normal state key, we would've bounded it in our package anyway.

For the case where there's no key "under" evil's normal state key, there's no loss other than the user *maybe* pressing 'i' in a readonly buffer and getting some sort of message.

> I'm against switching to normal state because that's not how Evil was designed. The motion state is here for a purpose.

Lets evaluate based on the tradeoffs of both approaches. I digress, I believe I read somewhere from the previous evil maintainer that evil-define-key itself wasn't a great design and using something like buffer-hooks and evil local keymaps is probably the better approach.

**Comment by noctuid** [comment] 2017-11-09 17:05
> The main downside of using normal state for read-only modes is that all the insertion keys (and that's lots of them) have to be unbound/rebound.

> For the case where there's no key "under" evil's normal state key, there's no loss other than the user maybe pressing 'i' in a readonly buffer and getting some sort of message.

Yes, this is the only downside I'm aware of. To prevent useless keys from being bound, a lot more keys would have to be overriden in normal state. Some/all motions don't make sense in some modes either though. I've never actually encountered the accidental keypress issue personally.

> As for the global question, off the top of my head there is some inheritance at work, but I have to look into this.

If you look at the state definitions, normal state `:enable`s (inherits from) motion state, and visual state enables both the normal and motion states.

> I'm against switching to normal state because that's not how Evil was designed. The motion state is here for a purpose.

The motion state keymap is useful to me because motions can be bound in a single keymap instead of in both the normal and visual state keymaps. I don't know if it was the original intention (it may very well have been) for motion state to be used for modes where insert keybindings don't make sense, but evil does consistently uses motion state in `evil-integration.el`. For me personally, this causes issues and solves a non-issue, but I wouldn't be opposed to motion state being the default as long is the behavior is configurable. 

> evil-define-key itself wasn't a great design and using something like buffer-hooks and evil local keymaps is probably the better approach

Well I'm really glad they didn't go with that approach.

**Comment by Ambrevar** [comment] 2017-11-09 19:31
Can you give some concrete binding examples to help understand better the issue?

**Comment by jojojames** [comment] 2017-11-10 02:02
I think the important point is using motion state seems to solve a non-issue (pressing editing commands like i in a mode that can't be edited will yield some error message) but causes issues (have to rebind keys for commands that are still appropriate in motion state but aren't bound in that state).

Is that a fair characterization? If it is, making normal state the default seems to be ideal. (Again, with the option to customize it between motion/normal.)

**Comment by noctuid** [comment] 2017-11-10 03:08
> Can you give some concrete binding examples to help understand better the issue?

Sure. For global keys, I prefer to use the global evil state keymaps. I make a lot of changes from the evil defaults. For example, I use `SPC` as a prefix key for file/buffer/workgroup management/switching. If I was using modes where motion state was the initial state, I would need to bind `SPC` in both the normal and motion states or bind it in just motion state and unbind the default `SPC` keybinding in normal state. I don't really like the latter solution because my `SPC` is a prefix key and not a motion.

There are both global keys that should never be overridden and global keys that it's okay to override (e.g. maybe the user uses a custom yank operator or something else). An alternative to the above for keys that should never be overridden is to use `evil-make-intercept-map`. If was using both normal and motion as default states, I would need to use `evil-make-intercept-map` for both the normal and motion states. Alternatively I could just have my `SPC` override `SPC` in all other states, but I don't want to do that because I have `SPC` bound to something else in visual state.

None of this requires a ton of extra configuration, but it's inelegant to me and a slight inconvenience. I prefer consistently using normal state and only using motion state for actual motions.

**Comment by Ambrevar** [comment] 2017-11-10 08:11
Wouldn't key translations (#5) solve this issue?  I.e. translating SPC key to whatever you like best in those mode, thus leaving SPC free for your global bindings.

I'm afraid that allowing for customizing that default state is not a generic solution.

1. Some modes like `diff-mode` have motion, normal and insert bindings.
2. While SPC conflicts with your global key and SPC is used in motion state, what about other conflicts (for other users) in normal state?  Some like using `,` as a leader key.  That would conflict too in normal mode, and thus changing the default state would not be a solution.

Your use case sounds exactly like what evil-leader is made for, isn't it?

**Comment by noctuid** [comment] 2017-11-10 15:49
> Wouldn't key translations (#5) solve this issue? I.e. translating SPC key to whatever you like best in those mode, thus leaving SPC free for your global bindings.

That's just an alternative to directly unbinding if I wanted to keep the `SPC` keybinding `evil-collection` makes on another key. That's something I'd have to do regardless of whether motion or normal was the default state. The extra annoyance is that I'd have to globally bind `SPC` (and all other global keys I use) in both the motion and normal states.

> Some modes like diff-mode have motion, normal and insert bindings.

I don't really like this solution for diff-mode but understand that it makes sense given the idea that motion state should be used for non-editable modes. It could be rewritten to use the mode hook and conditionally make buffer local keybindings. If the buffer was read only, the "default state" would be used and the appropriate keybindings would be bound in it. If the buffer was not read only, normal state would always be used. This would work with both values for the default state. Even if you'd rather not do this for modes where insertion sometimes but not always makes sense, I think it would be better to at least offer changing the default state as an option for modes where this isn't an issue.

> That would conflict too in normal mode, and thus changing the default state would not be a solution.

The issue is not the conflict (which is solvable in the same way regardless of whether a default state option is added). I brought up the conflict just to demonstrate that regardless of whether there is a conflict, global keybindings have to be bound in both the motion and normal states. Sure, helpers can be used to just do this at the same time, but I'd prefer not to need to do this in the first place.

> Your use case sounds exactly like what evil-leader is made for, isn't it?

`evil-leader` is a dead, poorly designed package with better alternatives, and `evil-make-intercept-map` alone is much better solution (as it is both simpler and will work in cases where `evil-leader` will not).

**Comment by Somelauw** [comment] 2017-11-10 23:19
I think there is a some ambiguity what evil-motion-state should be used for. One opinion is that it should be used for motions, but then why does it also bind `:`? The other opinion is that this state should be used for stuff that should be in read-only mode, but then why doesn't it bind `q` and `y`?
If this is the case, an issue can be made upstream posing this question.

**Comment by Somelauw** [comment] 2017-11-10 23:37
I don't think preserving `q` and `y` is that important.

- It's easy to do bind them in motion state
- The current convention says that `q` should quit
- Maybe `y` can be bound to something else in read-only modes (or would that be confusing?)

**Comment by noctuid** [comment] 2017-11-11 19:46
The intention of motion state isn't perfectly clear/consistent from `evil-maps.el` like you point out, but it definitely is also used for non-motions by default.

> but then why doesn't it bind q and y

Do you mean evil? Evil didn't used to bind `y` in motion state, but now it binds `y`/`Y` in both the normal and motion states. I don't know about the original intent, but motion state isn't just used for motions currently. Regardless of evil's intention I don't personally like ever using motion state. I think motion state was a poor design choice (at least how it's used now). It's often confusing to new users, how evil uses it doesn't match the name, and it doesn't even completely solve the issue of having useless keys bound. For example, it would make a lot more sense if there was another state/keymap for modes where motions don't sense (e.g. ediff-mode) where keys like `:` and `C-w` where bound. Having a different state for every different type of non-editing mode like this is just unnecessarily complicated to me though.

> I don't think preserving q and y is that important.

I think `y` is definitely useful and think it's probably better for `evil-collection` to be conservative and not override keys that could potentially be useful.

**Comment by jojojames** [comment] 2017-11-11 20:04
> Some modes like diff-mode have motion, normal and insert bindings.

I like the clever use of checking for state for diff-mode but I don't think it should be factored in when thinking about the default state (and/or customizable states) we use. I believe if we come to a good decision, we can meld diff-mode in a way that's still satisfactory.

As of now, I'm leaning towards 'normal as the default looking at @noctuid's points as well as my own experience with 'motion state. Being able to customize the default state also seems to be a reasonable goal on its own.

**Comment by jojojames** [comment] 2017-11-22 05:36
@Ambrevar If there's no opposition, I'd like to close this issue and move forward.

I'll begin moving the motion state maps to normal state and make any adjustments needed. The ones that use motion/normal state as a heuristic will probably have to be tweaked.

As for customizing the default state, I think that's a good idea too but I'll probably avoid doing it for now. (PRs welcome @noctuid).

**Comment by Ambrevar** [comment] 2017-11-22 08:51
Alright with moving forward.

How should we remove insertion keys from read-only modes?
What about a function that sets all the `i`, `a` and so forth to nil, called before setting the bindings?

**Comment by jojojames** [comment] 2017-11-22 08:59
Sounds good.

I'm ok with leaving it as is (let the user press the wrong key) but your suggestion works for me too.

**Comment by jojojames** [comment] 2017-12-13 17:15
As mentioned in the two commits, I believe it's reasonable to separate the issue of 'default state' and 'customizable default state'.

Lets move towards 'default state' going to normal state.

For customizable default state, we'll get there at some point. i.e. These two issues do not block each other.

**Comment by Ambrevar** [comment] 2017-12-13 17:23
For EWW: I actually ran into conflicts in normal state, which is why...
I've just wanted it online now, I'll resolve the conflict later.

**Comment by Ambrevar** [comment] 2017-12-13 18:17
So what's the plan of action?  Just move all the motion states to normal states?
What about a function that unbinds all insertion keys?

**Comment by noctuid** [comment] 2017-12-13 20:37
> What about a function that unbinds all insertion keys?

Personally I don't think it matters, but it wouldn't be hard to do this programmatically/concisely. If this is done, it should be done by remapping commands and not keys, e.g.:

```elisp
(evil-define-key 'normal Info-mode-map
  [remap evil-append] #'ignore)
```
A function could be created that just creates `ignore` keybindings for all insertion commands in a keymap.

**Comment by jojojames** [comment] 2017-12-14 01:51
> So what's the plan of action? Just move all the motion states to normal states?

Yes.

> What about a function that unbinds all insertion keys?

I do not think it is necessary. Even if it is, it shouldn't block ^.

**Comment by Ambrevar** [comment] 2017-12-14 08:06
Thanks for the tip, @noctuid, I hadn't thought of that.

I don't think we shoud neglect this however: in many modes pressing an insertion command will effectively get you into insertion mode, even though you cannot do anything from there.  You'll have to press ESC to resume back to normal mode.
In practice, this is mostly annoying when pressing those keys by mistakes: instead of wasting 1 keypress, we waste 2 (or more if we don't realize the mistake immediately).

Sounds like a nit, but it's fairly annoying and it does not look very polished.

**Comment by Ambrevar** [comment] 2017-12-14 08:10
There is a conflict with evil-mc (multiple cursors) minor mode: it defines `g-r-` prefixed bindings in normal mode.  The most obvious override is the `gr` (refresh) binding.

What shall we do here?

**Comment by jojojames** [comment] 2017-12-14 08:17
> I don't think we shoud neglect this however: in many modes pressing an insertion command will effectively get you into insertion mode, even though you cannot do anything from there. You'll have to press ESC to resume back to normal mode.

Sure, but again, that shouldn't block changing of the default to normal state.

As you said, maybe it's unpolished but it's not as bad as half the modes defaulting to motion and the other half defaulting to normal.

By the way, for modes where you can't insert anything, my experience has mostly been they are in readonly mode anyways. Pressing i or a / etc will just get you a user error message. I digress, we are in agreement anyway.

> There is a conflict with evil-mc (multiple cursors) minor mode: it defines g-r- prefixed bindings in normal mode. The most obvious override is the gr (refresh) binding.

> What shall we do here?

I'm not a big fan of those keys evil-mc decided to take. Not only did it take gr, it also took c-n, c-p, m-n, m-p and c-t.

I force removed them myself.

```
  (defun +remove-evil-mc-keymap (&rest _args)
    "Brute force remove `evil-mc-key-map' from `evil-mode-map-alist'."
    (when-let* ((evil-mc-map (assq 'evil-mc-mode evil-mode-map-alist)))
      (setq evil-mode-map-alist
            (delq evil-mc-map evil-mode-map-alist))))

  (advice-add 'evil-normalize-keymaps :after '+remove-evil-mc-keymap)
```

My suggestion is to provide our own evil-mc layer (an evil layer above an evil layer :)) and disable those keys so that they are my in line with evil-collection or request a change of defaults for evil-mc.

**Comment by Ambrevar** [comment] 2017-12-14 08:21
Which bindings have you set up for evil-mc then?

**Comment by Ambrevar** [comment] 2017-12-14 08:23
We might not have to go down that road at all anyways: I don't think evil-mc ever makes sense in special modes, so we could just tell the user to enable it for text modes and programming modes.

**Comment by Ambrevar** [comment] 2017-12-14 08:24
```
  (add-hook 'text-mode-hook 'evil-mc-mode)
  (add-hook 'prog-mode-hook 'evil-mc-mode)
```

**Comment by jojojames** [comment] 2017-12-14 08:26
```
(defun +setup-evil-mc-keys-locally ()
    "Set up key bindings for `evil-mc' using `evil-normal-state-local-map'."
    (dolist (evil-map-symbol '(evil-normal-state-local-map
                               evil-visual-state-local-map
                               evil-motion-state-local-map))
      (let ((map (symbol-value evil-map-symbol)))
        (define-key map (kbd "C-=") '+evil-mc-make-cursors-in-defun)
        (define-key map (kbd "C-<") 'evil-mc-insert-vertical-cursors)
        (define-key map (kbd "C->") 'evil-mc-append-vertical-cursors)
        (define-key map (kbd "M-n") 'evil-mc-make-and-goto-next-cursor)
        (define-key map (kbd "M-p") 'evil-mc-make-and-goto-prev-cursor)
        (define-key map (kbd "C-n") 'evil-mc-make-and-goto-next-match)
        (define-key map (kbd "C-p") 'evil-mc-make-and-goto-prev-match)
        (define-key map (kbd "C-*") 'evil-mc-make-all-cursors))))
```

I am not happy with these bindings though and would like to change them to something more appropriate at some point..

I might end up going with something like what multiple-cursors does.

```
(global-set-key (kbd "C->") 'mc/mark-next-like-this)
(global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
(global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)

;; ETC
```

**Comment by noctuid** [comment] 2017-12-14 19:28
> Sounds like a nit, but it's fairly annoying and it does not look very polished.

I think the necessary configuration would be small enough to be worth doing. I agree this change can come later though.

> Pressing i or a / etc will just get you a user error message. 

I haven't experienced this. In readonly modes, usually it will go to insert state unless you try to use `c`. I used to use this if I ever needed the default keybindings for something (but that's really what `C-z` should be for).

I don't use multiple cursors, but I think even if it did make sense in some of these modes, I think it would be fine to let the user decide how to handle it.

**Comment by jojojames** [comment] 2017-12-15 04:21
> I haven't experienced this. In readonly modes, usually it will go to insert state unless you try to use c. I used to use this if I ever needed the default keybindings for something (but that's really what C-z should be for).

Maybe I'm mistaken then. That was what I recalled the behavior to be on some of the modes I used.

**Comment by jojojames** [comment] 2018-01-10 03:35
I've started moving over most modes to normal state. There's still a few modes I haven't touched (because I don't use that particular package) but most should be in normal state by default now.

**Comment by Ambrevar** [comment] 2018-01-10 09:40
I'm very sorry for not being responsive on this: I haven't touched Emacs development for a couple of weeks now.  I'll come back to it very soon.

We've still got to answer the issue of disabling insert most for read-only modes.

**Comment by jojojames** [comment] 2018-01-10 17:48
How do we intend to handle modes that can be shifted from read-only to write?

**Comment by jojojames** [comment] 2018-01-10 17:49
Again, I'd prefer shifting the states to normal and then solving the 'insert' problem after.

**Comment by Ambrevar** [comment] 2018-02-22 17:38
I've finally pushed the changes.  (About time...)

I have switched all modes but `diff` to normal state.
As for `diff`, the dual `motion`/`normal` makes sense in my opinion.  If we really want to get rid of the motion state here, we need to define a dedicated map which inherits from the normal map, I suppose.

@jojojames Feel free to close this issue if you are happy with the changes.

**Comment by jojojames** [comment] 2018-02-23 02:50
@Ambrevar Nice!

@noctuid Do you still want the 'customizable' part for this? It *might* be nice to do so too but I don't have a use case for it so a PR would have to come through from someone else probably.

**Comment by noctuid** [comment] 2018-02-23 20:45
@Ambrevar Nice. While it's not a huge issue, I think the alternative I proposed earlier for diff mode (using buffer-local keybindings/`evil-local-set-key` in normal state based on whether the buffer is read-only instead of altering diff-mode-map) would be preferable.

@jojojames No, I can't think of a use case for it either.

**Comment by Ambrevar** [comment] 2018-02-23 23:56
How do you switch from one binding set to another?  Having a dedicated minor mode map would make it easier I think.

**Comment by noctuid** [comment] 2018-02-24 04:53
You could just reset the local keymap and then make the keybindings again or unbind the specific keys. Though this would make it harder for the user to customize the keybindings, so I agree it's not ideal and having a minor mode would be preferable. Binding the basic keys in normal state in `diff-mode-map` and having a minor mode for read-only for the extra keybindings makes more sense.

**Comment by Ambrevar** [comment] 2018-02-24 08:05
Shall we go that way or simply leave it to the motion state?

**Comment by jojojames** [comment] 2018-02-25 00:57
If diff mode was the only mode, it might not be necessary unless someone wanted to do it.

As for setting a precedence, we might want to go with a minor-mode if that's the cleanest way to do it.

**Comment by Ambrevar** [comment] 2018-02-25 08:29
What might not be necessary?

**Comment by jojojames** [comment] 2018-02-25 08:56
The extra minor-mode.

**Comment by noctuid** [comment] 2018-02-27 01:04
I think the minor mode would be preferable for consistency, but it's not a major issue (at least not for me; I don't often use diff-mode)

**Comment by jojojames** [comment] 2018-02-28 01:44
I'd like to change it once I have time. One small problem is I don't use diff-mode very often.

**Comment by jojojames** [comment] 2018-03-31 17:26
Closing in favor of https://github.com/emacs-evil/evil-collection/issues/114

**Closed by jojojames** 2018-03-31 17:26 UTC
Labels: MELPA
