### ISSUE TITLE
Evil-scroll-down Error: (wrong-type-argument integer-or-marker-p nil)

### ISSUE THREAD

**Issue by duzaichuan** [emacs-evil/evil-collection#189] opened 2018-08-07 07:19 UTC
In eww and nov mode, when i scroll down, the error message emerges.

Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  evil-scroll-down(nil)
  funcall-interactively(evil-scroll-down nil)
  call-interactively(evil-scroll-down nil nil)
  command-execute(evil-scroll-down)

No such issue in prog-mode and text-mode.

Any ideas? Thanks.

**Comment by duzaichuan** [comment] 2018-08-07 07:40
My config is ugly listed. Sorry for this, i failed to make it nice.
`
(use-package evil
  :ensure t
  :diminish evil-mode

  :init
  (progn
    (setq evil-want-integration nil) 
    (use-package evil-leader
      :ensure t
      :init (global-evil-leader-mode)
      :config
      (progn
	(evil-leader/set-leader "SPC")
	(evil-leader/set-key "gs" 'magit-status)
	(evil-leader/set-key "gu" 'browse-url-at-point))) )

  :config
  (progn
    (evil-mode 1)
    (setq evil-cross-lines t)
    (setq evil-move-cursor-back nil)
    (setq evil-want-C-u-scroll t)
    (setcdr evil-insert-state-map nil)
    (define-key evil-insert-state-map [escape] 'evil-normal-state)
    ;; Make evil-mode up/down operate in screen lines instead of logical lines
    (define-key evil-motion-state-map "j" 'evil-next-visual-line)
    (define-key evil-motion-state-map "k" 'evil-previous-visual-line)
    ;; Also in visual mode
    (define-key evil-visual-state-map "j" 'evil-next-visual-line)
    (define-key evil-visual-state-map "k" 'evil-previous-visual-line)
    (defun du/evil-record-macro ()
      (interactive)
      (if buffer-read-only
	  (quit-window)
	(call-interactively 'evil-record-macro)))
    ;; evil quit-window and evil-record-macro integration
    (with-eval-after-load 'evil-maps
      (define-key evil-normal-state-map (kbd "q") 'du/evil-record-macro)) ))
`

(use-package evil-collection
  :defer 0.1
  :ensure t
  :custom (evil-collection-setup-minibuffer t)
  :config
  (progn
    (evil-collection-init)
    (with-eval-after-load 'pdf-tools
      (require 'evil-collection-pdf) (evil-collection-pdf-setup)) ))

**Comment by Ambrevar** [comment] 2018-08-07 07:48
To insert fenced code, you can surround it with lines containing
    ```
More Markdown help here: https://guides.github.com/features/mastering-markdown/

I cannot reproduce your issue.  I haven't tried your config though.  Can you try from a vanilla config?

**Comment by duzaichuan** [comment] 2018-08-07 07:52
@Ambrevar Thanks! And I will try that.

**Comment by duzaichuan** [comment] 2018-08-11 20:37
I found a same open issue reported in evil repo https://github.com/emacs-evil/evil/issues/713.

**Comment by Ambrevar** [comment] 2018-08-11 22:12
Right, I can reproduce with `C-d`.  I'm closing this since this is an Evil issue.

**Closed by Ambrevar** 2018-08-11 22:12 UTC
